# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Freakshow 13
description: >- # this means to ignore newlines until "baseurl:"
  Sonic Adventure but with 13 characters? Sign me up!
baseurl: "/freakshow-13" # the subpath of your site, e.g. /blog
url: "https://vitimesthree.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# These are custom variables written by me (vitimesthree) to make it easier to access assets.
imageurl: "/freakshow-13/assets/images/"
audiourl: "/freakshow-13/assets/audio/"
videourl: "/freakshow-13/assets/videos/"

# Defaults. For example, this is useful for defining a default layout for the entire site.
defaults:
  - scope:
      path: ""
    values:
      layout: "default"